"""baseline schema — entire current schema in one revision

Revision ID: 20260626_000001
Revises:
Create Date: 2026-06-26

Squashed baseline (codex review B1). The prior incremental migrations assumed a
pre-existing schema — the very first one had ``down_revision = None`` yet its
opening op created ``refresh_tokens`` with a FK to ``users`` and altered
``users``, so ``alembic upgrade head`` could never bootstrap an EMPTY database.
The backend tests hid this because they build the schema with
``Base.metadata.create_all`` directly rather than running migrations.

This single revision creates the complete current schema straight from the
SQLAlchemy models, so a fresh production database is provisioned with one
``alembic upgrade head``. Because it is generated from the very metadata the app
and tests already use, it cannot drift from the models. Future schema changes
get normal autogenerated incremental migrations chained after this baseline.
"""

import app.models  # noqa: F401 — registers every table on Base.metadata
from alembic import op
from app.core.database import Base

revision = "20260626_000001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
